var invert = require('invert-obj');

function AllocRejCode (allocRejCode) {
  this.message = allocRejCode;
}

AllocRejCode.prototype.value = function () {
  return this.message;
};


AllocRejCode.Keys = {
  'UNKNOWN_OR_MISSING_ACCOUNT': '0',
  'INCORRECT_OR_MISSING_BLOCK_QUANTITY': '1',
  'INCORRECT_OR_MISSING_AVERAGE_PRICE': '2',
  'UNKNOWN_EXECUTING_BROKER_MNEMONIC': '3',
  'INCORRECT_OR_MISSING_COMMISSION': '4',
  'UNKNOWN_ORDERID': '5',
  'UNKNOWN_LISTID': '6',
  'OTHER': '7',
  'INCORRECT_OR_MISSING_ALLOCATED_QUANTITY': '8',
  'CALCULATION_DIFFERENCE': '9',
  'UNKNOWN_OR_STALE_EXECID': '10',
  'MISMATCHED_DATA': '11',
  'UNKNOWN_CLORDID': '12',
  'WAREHOUSE_REQUEST_REJECTED': '13',
  'DUPLICATE_OR_MISSING_INDIVIDUALALLOCID': '14',
  'TRADE_NOT_RECOGNIZED': '15',
  'TRADE_PREVIOUSLY_ALLOCATED': '16',
  'INCORRECT_OR_MISSING_INSTRUMENT': '17',
  'INCORRECT_OR_MISSING_SETTLEMENT_DATE': '18',
  'INCORRECT_OR_MISSING_FUND_ID_OR_FUND_NAME': '19',
  'INCORRECT_OR_MISSING_SETTLEMENT_INSTRUCTIONS': '20',
  'INCORRECT_OR_MISSING_FEES': '21',
  'INCORRECT_OR_MISSING_TAX': '22',
  'UNKNOWN_OR_MISSING_PARTY': '23',
  'INCORRECT_OR_MISSING_SIDE': '24',
  'INCORRECT_OR_MISSING_NET_MONEY': '25',
  'INCORRECT_OR_MISSING_TRADE_DATE': '26',
  'INCORRECT_OR_MISSING_SETTLEMENT_CURRENCY_INSTRUCTIONS': '27',
  'OTHER_1': '99',
};

AllocRejCode.Tag = '88';

AllocRejCode.Type = 'INT';

AllocRejCode.Values = invert(AllocRejCode.Keys);

module.exports = AllocRejCode;