var invert = require('invert-obj');

function CustOrderHandlingInst (custOrderHandlingInst) {
  this.message = custOrderHandlingInst;
}

CustOrderHandlingInst.prototype.value = function () {
  return this.message;
};


CustOrderHandlingInst.Keys = {
  PHONE_SIMPLE: 'A',
  G_ORDER: 'G',
  ADD_ON_ORDER: 'ADD',
  PHONE_COMPLEX: 'B',
  ALL_OR_NONE: 'AON',
  FCM_PROVIDED_SCREEN: 'C',
  OTHER_PROVIDED_SCREEN: 'D',
  CONDITIONAL_ORDER: 'CND',
  CASH_NOT_HELD: 'CNH',
  CLIENT_PROVIDED_PLATFORM_CONTROLLED_BY_FCM: 'E',
  CLIENT_PROVIDED_PLATFORM_DIRECT_TO_EXCHANGE: 'F',
  DELIVERY_INSTRUCTIONS_CASH: 'CSH',
  DIRECTED_ORDER: 'DIR',
  ALGO_ENGINE: 'H',
  DISCRETIONARY_LIMIT_ORDER: 'DLO',
  EXCHANGE_FOR_PHYSICAL_TRANSACTION: 'E.W',
  PRICE_AT_EXECUTION: 'J',
  FILL_OR_KILL: 'FOK',
  DESK_ELECTRONIC: 'W',
  DESK_PIT: 'X',
  CLIENT_ELECTRONIC: 'Y',
  INTRADAY_CROSS: 'IDX',
  IMBALANCE_ONLY: 'IO',
  CLIENT_PIT: 'Z',
  IMMEDIATE_OR_CANCEL: 'IOC',
  INTERMARKET_SWEEP_ORDER: 'ISO',
  LIMIT_ON_OPEN: 'LOO',
  LIMIT_ON_CLOSE: 'LOC',
  MARKET_AT_OPEN: 'MAO',
  MARKET_AT_CLOSE: 'MAC',
  MARKET_ON_OPEN: 'MOO',
  MARKET_ON_CLOSE: 'MOC',
  MERGER_RELATED_TRANSFER_POSITION: 'MPT',
  MINIMUM_QUANTITY: 'MQT',
  MARKET_TO_LIMIT: 'MTL',
  DELIVERY_INSTRUCTIONS_NEXT_DAY: 'ND',
  NOT_HELD: 'NH',
  OPTIONS_RELATED_TRANSACTION: 'OPT',
  OVER_THE_DAY: 'OVD',
  PEGGED: 'PEG',
  RESERVE_SIZE_ORDER: 'RSV',
  STOP_STOCK_TRANSACTION: 'S.W',
  SCALE: 'SCL',
  DELIVERY_INSTRUCTIONS_SELLERS_OPTION: 'SLR',
  TIME_ORDER: 'TMO',
  TRAILING_STOP: 'TS',
  WORK: 'WRK',
  STAY_ON_OFFERSIDE: 'F0',
  GO_ALONG: 'F3',
  PARTICIPATE_DO_NOT_INITIATE: 'F6',
  STRICT_SCALE: 'F7',
  TRY_TO_SCALE: 'F8',
  STAY_ON_BIDSIDE: 'F9',
  NO_CROSS: 'FA',
  OK_TO_CROSS: 'FB',
  CALL_FIRST: 'FC',
  PERCENT_OF_VOLUME: 'FD',
  REINSTATE_ON_SYSTEM_FAILURE: 'FH',
  INSTITUTION_ONLY: 'FI',
  REINSTATE_ON_TRADING_HALT: 'FJ',
  CANCEL_ON_TRADING_HALF: 'FK',
  LAST_PEG: 'FL',
  MID_PRICE_PEG: 'FM',
  NON_NEGOTIABLE: 'FN',
  OPENING_PEG: 'FO',
  MARKET_PEG: 'FP',
  CANCEL_ON_SYSTEM_FAILURE: 'FQ',
  PRIMARY_PEG: 'FR',
  SUSPEND: 'FS',
  FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER: 'FT',
  PEG_TO_VWAP: 'FW',
  TRADE_ALONG: 'FX',
  TRY_TO_STOP: 'FY',
  CANCEL_IF_NOT_BEST: 'FZ',
  STRICT_LIMIT: 'Fb',
  IGNORE_PRICE_VALIDITY_CHECKS: 'Fc',
  PEG_TO_LIMIT_PRICE: 'Fd',
  WORK_TO_TARGET_STRATEGY: 'Fe',
};

CustOrderHandlingInst.Tag = '1031';

CustOrderHandlingInst.Type = 'MULTIPLESTRINGVALUE';

CustOrderHandlingInst.Values = invert(CustOrderHandlingInst.Keys);

module.exports = CustOrderHandlingInst;