var invert = require('invert-obj');

function ExecInst (execInst) {
  this.message = execInst;
}

ExecInst.prototype.value = function () {
  return this.message;
};


ExecInst.Keys = {
  'STAY_ON_OFFER_SIDE': '0',
  'NOT_HELD': '1',
  'WORK': '2',
  'GO_ALONG': '3',
  'OVER_THE_DAY': '4',
  'HELD': '5',
  'PARTICIPATE_DONT_INITIATE': '6',
  'STRICT_SCALE': '7',
  'TRY_TO_SCALE': '8',
  'STAY_ON_BID_SIDE': '9',
  'NO_CROSS': 'A',
  'OK_TO_CROSS': 'B',
  'CALL_FIRST': 'C',
  'PERCENT_OF_VOLUME': 'D',
  'DO_NOT_INCREASE_DNI': 'E',
  'DO_NOT_REDUCE_DNR': 'F',
  'ALL_OR_NONE_AON': 'G',
  'REINSTATE_ON_SYSTEM_FAILURE': 'H',
  'INSTITUTIONS_ONLY': 'I',
  'REINSTATE_ON_TRADING_HALT': 'J',
  'CANCEL_ON_TRADING_HALT': 'K',
  'LAST_PEG': 'L',
  'MID_PRICE_PEG': 'M',
  'NON_NEGOTIABLE': 'N',
  'OPENING_PEG': 'O',
  'MARKET_PEG': 'P',
  'CANCEL_ON_SYSTEM_FAILURE': 'Q',
  'PRIMARY_PEG': 'R',
  'SUSPEND': 'S',
  'FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER': 'T',
  'CUSTOMER_DISPLAY_INSTRUCTION': 'U',
  'NETTING': 'V',
  'PEG_TO_VWAP': 'W',
  'TRADE_ALONG': 'X',
  'TRY_TO_STOP': 'Y',
  'CANCEL_IF_NOT_BEST': 'Z',
  'TRAILING_STOP_PEG': 'a',
  'STRICT_LIMIT': 'b',
  'IGNORE_PRICE_VALIDITY_CHECKS': 'c',
  'PEG_TO_LIMIT_PRICE': 'd',
  'WORK_TO_TARGET_STRATEGY': 'e',
  'INTERMARKET_SWEEP': 'f',
  'EXTERNAL_ROUTING_ALLOWED': 'g',
  'EXTERNAL_ROUTING_NOT_ALLOWED': 'h',
  'IMBALANCE_ONLY': 'i',
  'SINGLE_EXECUTION_REQUESTED_FOR_BLOCK_TRADE': 'j',
  'BEST_EXECUTION': 'k',
  'SUSPEND_ON_SYSTEM_FAILURE': 'l',
  'SUSPEND_ON_TRADING_HALT': 'm',
  'REINSTATE_ON_CONNECTION_LOSS': 'n',
  'CANCEL_ON_CONNECTION_LOSS': 'o',
  'SUSPEND_ON_CONNECTION_LOSS': 'p',
  'RELEASE': 'q',
  'EXECUTE_AS_DELTA_NEUTRAL_USING_VOLATILITY_PROVIDED': 'r',
  'EXECUTE_AS_DURATION_NEUTRAL': 's',
  'EXECUTE_AS_FX_NEUTRAL': 't',
  'MINIMUM_GUARANTEED_FILL_ELIGIBLE': 'u',
  'BYPASS_NON_DISPLAYED_LIQUIDITY': 'v',
  'LOCK': 'w',
  'IGNORE_NOTIONAL_VALUE_CHECKS': 'x',
};

ExecInst.Tag = '18';

ExecInst.Type = 'MULTIPLECHARVALUE';

ExecInst.Values = invert(ExecInst.Keys);

module.exports = ExecInst;