var invert = require('invert-obj');

function OrdRejReason (ordRejReason) {
  this.message = ordRejReason;
}

OrdRejReason.prototype.value = function () {
  return this.message;
};


OrdRejReason.Keys = {
  'BROKER_EXCHANGE_OPTION': '0',
  'UNKNOWN_SYMBOL': '1',
  'EXCHANGE_CLOSED': '2',
  'ORDER_EXCEEDS_LIMIT': '3',
  'TOO_LATE_TO_ENTER': '4',
  'UNKNOWN_ORDER': '5',
  'DUPLICATE_ORDER': '6',
  'DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER': '7',
  'STALE_ORDER': '8',
  'TRADE_ALONG_REQUIRED': '9',
  'INVALID_INVESTOR_ID': '10',
  'UNSUPPORTED_ORDER_CHARACTERISTIC': '11',
  'SURVEILLENCE_OPTION': '12',
  'INCORRECT_QUANTITY': '13',
  'INCORRECT_ALLOCATED_QUANTITY': '14',
  'UNKNOWN_ACCOUNT': '15',
  'PRICE_EXCEEDS_CURRENT_PRICE_BAND': '16',
  'INVALID_PRICE_INCREMENT': '18',
  'REFERENCE_PRICE_NOT_AVAILABLE': '19',
  'NOTIONAL_VALUE_EXCEEDS_THRESHOLD': '20',
  'ALGORITHM_RISK_THRESHOLD_BREACHED': '21',
  'SHORT_SELL_NOT_PERMITTED': '22',
  'SHORT_SELL_REJECTED_DUE_TO_SECURITY_PRE_BORROW_RESTRICTION': '23',
  'SHORT_SELL_REJECTED_DUE_TO_ACCOUNT_PRE_BORROW_RESTRICTION': '24',
  'INSUFFICIENT_CREDIT_LIMIT': '25',
  'EXCEEDED_CLIP_SIZE_LIMIT': '26',
  'EXCEEDED_MAXIMUM_NOTIONAL_ORDER_AMOUNT': '27',
  'EXCEEDED_DV01_PV01_LIMIT': '28',
  'EXCEEDED_CS01_LIMIT': '29',
  'OTHER': '99',
};

OrdRejReason.Tag = '103';

OrdRejReason.Type = 'INT';

OrdRejReason.Values = invert(OrdRejReason.Keys);

module.exports = OrdRejReason;