var invert = require('invert-obj');

function PartyIDSource (partyIdsource) {
  this.message = partyIdsource;
}

PartyIDSource.prototype.value = function () {
  return this.message;
};


PartyIDSource.Keys = {
  'UK_NATIONAL_INSURANCE_OR_PENSION_NUMBER': '6',
  'KOREAN_INVESTOR_ID': '1',
  'DIRECTED_BROKER_THREE_CHARACTER_ACRONYM_AS_DEFINED_IN_ISITC_ETC_BEST_PRACTICE_GUIDELINES_DOCUMENT': 'I',
  'BIC': 'B',
  'US_SOCIAL_SECURITY_NUMBER': '7',
  'TAIWANESE_QUALIFIED_FOREIGN_INVESTOR_ID_QFII_FID': '2',
  'GENERALLY_ACCEPTED_MARKET_PARTICIPANT_IDENTIFIER': 'C',
  'US_EMPLOYER_OR_TAX_ID_NUMBER': '8',
  'TAIWANESE_TRADING_ACCT': '3',
  'PROPRIETARY_CUSTOM_CODE': 'D',
  'AUSTRALIAN_BUSINESS_NUMBER': '9',
  'MALAYSIAN_CENTRAL_DEPOSITORY_NUMBER': '4',
  'ISO_COUNTRY_CODE': 'E',
  'AUSTRALIAN_TAX_FILE_NUMBER': 'A',
  'CHINESE_INVESTOR_ID': '5',
  'SETTLEMENT_ENTITY_LOCATION': 'F',
  'MIC': 'G',
  'TAX_ID': 'J',
  'CSD_PARTICIPANT_MEMBER_CODE': 'H',
  'AUSTRALIAN_COMPANY_NUMBER': 'K',
  'AUSTRALIAN_REGISTERED_BODY_NUMBER': 'L',
  'CFTC_REPORTING_FIRM_IDENTIFIER': 'M',
  'LEGAL_ENTITY_IDENTIFIER_LEI': 'N',
  'INTERIM_IDENTIFIER': 'O',
};

PartyIDSource.Tag = '447';

PartyIDSource.Type = 'CHAR';

PartyIDSource.Values = invert(PartyIDSource.Keys);

module.exports = PartyIDSource;