var invert = require('invert-obj');

function PosAmtType (posAmtType) {
  this.message = posAmtType;
}

PosAmtType.prototype.value = function () {
  return this.message;
};


PosAmtType.Keys = {
  'CASH_AMOUNT': 'CASH',
  'CASH_RESIDUAL_AMOUNT': 'CRES',
  'FINAL_MARK_TO_MARKET_AMOUNT': 'FMTM',
  'INCREMENTAL_MARK_TO_MARKET': 'IMTM',
  'PREMIUM_AMOUNT': 'PREM',
  'START_OF_DAY_MARK_TO_MARKET': 'SMTM',
  'TRADE_VARIATION_AMOUNT': 'TVAR',
  'VALUE_ADJUSTED_AMOUNT': 'VADJ',
  'SETTLEMENT_VALUE': 'SETL',
  'INITIAL_TRADE_COUPON_AMOUNT': 'ICPN',
  'ACCRUED_COUPON_AMOUNT': 'ACPN',
  'COUPON_AMOUNT': 'CPN',
  'INCREMENTAL_ACCRUED_COUPON': 'IACPN',
  'COLLATERALIZED_MARK_TO_MARKET': 'CMTM',
  'INCREMENTAL_COLLATERALIZED_MARK_TO_MARKET': 'ICMTM',
  'COMPENSATION_AMOUNT': 'DLV',
  'TOTAL_BANKED_AMOUNT': 'BANK',
  'TOTAL_COLLATERALIZED_AMOUNT': 'COLAT',
  'LONG_PAIRED_SWAP_OR_SWAPTION_NOTIONAL_VALUE': 'LSNV',
  'SHORT_PAIRED_SWAP_OR_SWAPTION_NOTIONAL_VALUE': 'SSNV',
  'START_OF_DAY_ACCRUED_COUPON': 'SACPN',
  'NET_PRESENT_VALUE': 'NPV',
  'START_OF_DAY_NET_PRESENT_VALUE': 'SNPV',
  'NET_CASH_FLOW': 'NCF',
  'PRESENT_VALUE_OF_ALL_FEES': 'PVFEES',
  'PRESENT_VALUE_OF_ONE_BASIS_POINTS': 'PV01',
  'THE_FIVE_YEAR_EQUIVALENT_NOTIONAL_AMOUNT': '5YREN',
  'UNDISCOUNTED_MARK_TO_MARKET': 'UMTM',
  'MARK_TO_MODEL': 'MTD',
  'MARK_TO_MARKET_VARIANCE': 'VMTM',
  'MARK_TO_MODEL_VARIANCE': 'VMTD',
  'UPFRONT_PAYMENT': 'UPFRNT',
};

PosAmtType.Tag = '707';

PosAmtType.Type = 'STRING';

PosAmtType.Values = invert(PosAmtType.Keys);

module.exports = PosAmtType;