var invert = require('invert-obj');

function TrdType (trdType) {
  this.message = trdType;
}

TrdType.prototype.value = function () {
  return this.message;
};


TrdType.Keys = {
  REGULAR_TRADE: '0',
  BLOCK_TRADE: '1',
  EXCHANGE_FOR_PHYSICAL: '2',
  TRANSFER: '3',
  LATE_TRADE: '4',
  T_TRADE: '5',
  WEIGHTED_AVERAGE_PRICE_TRADE: '6',
  BUNCHED_TRADE: '7',
  LATE_BUNCHED_TRADE: '8',
  PRIOR_REFERENCE_PRICE_TRADE: '9',
  AFTER_HOURS_TRADE: '10',
  EXCHANGE_FOR_RISK: '11',
  EXCHANGE_FOR_SWAP: '12',
  EXCHANGE_OF_FUTURES_FOR_IN_MARKET_FUTURES: '13',
  EXCHANGE_OF_OPTIONS_FOR_OPTIONS: '14',
  TRADING_AT_SETTLEMENT: '15',
  ALL_OR_NONE: '16',
  FUTURES_LARGE_ORDER_EXECUTION: '17',
  EXCHANGE_OF_FUTURES_FOR_EXTERNAL_MARKET_FUTURES: '18',
  OPTION_INTERIM_TRADE: '19',
  OPTION_CABINET_TRADE: '20',
  PRIVATELY_NEGOTIATED_TRADE: '22',
  SUBSTITUTION_OF_FUTURES_FOR_FORWARDS: '23',
  ERROR_TRADE: '24',
  SPECIAL_CUM_DIVIDEND: '25',
  SPECIAL_EX_DIVIDEND: '26',
  SPECIAL_CUM_COUPON: '27',
  SPECIAL_EX_COUPON: '28',
  CASH_SETTLEMENT: '29',
  SPECIAL_PRICE: '30',
  GUARANTEED_DELIVERY: '31',
  SPECIAL_CUM_RIGHTS: '32',
  SPECIAL_EX_RIGHTS: '33',
  SPECIAL_CUM_CAPITAL_REPAYMENTS: '34',
  SPECIAL_EX_CAPITAL_REPAYMENTS: '35',
  SPECIAL_CUM_BONUS: '36',
  SPECIAL_EX_BONUS: '37',
  BLOCK_TRADE_1: '38',
  WORKED_PRINCIPAL_TRADE: '39',
  BLOCK_TRADES: '40',
  NAME_CHANGE: '41',
  PORTFOLIO_TRANSFER: '42',
  PROROGATION_BUY: '43',
  PROROGATION_SELL: '44',
  OPTION_EXERCISE: '45',
  DELTA_NEUTRAL_TRANSACTION: '46',
  FINANCING_TRANSACTION: '47',
  NON_STANDARD_SETTLEMENT: '48',
  DERIVATIVE_RELATED_TRANSACTION: '49',
  PORTFOLIO_TRADE: '50',
  VOLUME_WEIGHTED_AVERAGE_TRADE: '51',
  EXCHANGE_GRANTED_TRADE: '52',
  REPURCHASE_AGREEMENT: '53',
  OTC: '54',
  EXCHANGE_BASIS_FACILITY: '55',
  OPENING_TRADE: '56',
  NETTED_TRADE: '57',
  BLOCK_SWAP_TRADE: '58',
  CREDIT_EVENT_TRADE: '59',
  SUCCESSION_EVENT_TRADE: '60',
  GIVE_UP_GIVE_IN_TRADE: '61',
  DARK_TRADE: '62',
  TECHNICAL_TRADE: '63',
  BENCHMARK: '64',
  PACKAGE_TRADE: '65',
};

TrdType.Tag = '828';

TrdType.Type = 'INT';

TrdType.Values = invert(TrdType.Keys);

module.exports = TrdType;